title:          Dalp
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/temp"
url:            "" #TODO

author:
  name:         Daniel Alp
  url:          https://github.com/Daniel-Alp
  email:        dalp@uwaterloo.ca

markdown:       kramdown
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

permalink:      /:year-:month-:day/:title

exclude: [ Gemfile, Gemfile.lock ]

disqus:         dalp